spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prevencion_riesgos
    username: root
    password: Admin.123

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true






















#server.port=9898
# Configuration for MySQL Database
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.datasource.url=jdbc:mysql://localhost:3306/prevencion_riesgos
#spring.datasource.username=root
#spring.datasource.password=Admin.123
#spring.jpa.hibernate.ddl-auto=update
#spring.mvc.view.prefix=/WEB-INF/
#spring.mvc.hiddenmethod.filter.enabled=true

#spring.jpa.show-sql: true
